USE employee_db;

INSERT INTO department (name) VALUES
    ('Quest'),
    ('Hobbiton'),
    ('Mirkwood'),
    ('Rohan'),
    ('Gondor'),
    ('Shire'),
    ('Buckland'),
    ('Erebor'),
    ('Rivendell'),
    ('White Council'),
    ('Isengard'),
    ('Mordor'),
    ('Lothlorien'),
    ('Dale'),
    ('Durin''s Folk'),
    ('Ring Bearers'),
    ('Middle Earth'),
    ('Fellowship of the Ring'),
    ('Master of Rivendell'),
    ('Rohan'),
    ('Gondor'),
    ('Shire'),
    ('Lothlorien'),
    ('Erebor'),
    ('Dwarves'),
    ('Hobbits'),
    ('Isengard'),
    ('Mordor'),
    ('Elves'),
    ('King of Gondor');
   

    INSERT INTO role (title, salary, department_id) VALUES
    ('Manager', 100000, 1),
    ('Assistant to the Ring Bearer', 100000, 1),
    ('Ring Bearer', 10000000, 1),
    ('Burglar', 100000, 2),
    ('Wizard', 100000, 3),
    ('King of Gondor', 100000, 1),
    ('Prince of Mirkwood', 100000, 4),
    ('Lord of Aglarond', 100000, 1),
    ('Captain of the White Tower', 100000, 5),
    ('Master of Buckland', 100000, 6),
    ('Thain of the Shire', 100000, 7),
    ('Guide', 100000, 8),
    ('Head of the White Council', 100000, 9),
    ('Dark Lord', 100000, 10),
    ('Lord of Rivendell', 100000, 11),
    ('Lady of Lothlorien', 100000, 12),
    ('Lord of Lothlorien', 100000, 13),
    ('Queen of Gondor', 100000, 14),
    ('King of Dale', 100000, 15),
    ('Prince of Dale', 100000, 4),
    ('King of Dale', 100000, 3),
    ('King of Durin''s Folk', 100000, 1),
    ('King of Durin''s Fo', 200000, 2);

    INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES
    ('Frodo', 'Baggins', 1, 1),
    ('Samwise', 'Gamgee', 2, 1),
    ('Bilbo', 'Baggins', 3, 1),
    ('Gandalf', 'the Grey', 4, 1),
    ('Aragorn', 'Elessar', 5, 1),
    ('Legolas', 'Greenleaf', 6, 1),
    ('Gimli', 'son of Gloin', 7, 1),
    ('Boromir', 'son of Denethor', 8, 1),
    ('Meriadoc', 'Brandybuck', 9, 1),
    ('Peregrin', 'Took', 10, 1),
    ('Gollum', 'Smeagol', 11, 1),
    ('Saruman', 'the White', 12, 1),
    ('Sauron', 'the Dark Lord', 13, 1),
    ('Elrond', 'Half-elven', 14, 1),
    ('Galadriel', 'Lady of Lothlorien', 15, 1),
    ('Celeborn', 'Lord of Lothlorien', 16, 1),
    ('Arwen', 'Evenstar', 17, 1),
    ('Bard', 'the Bowman', 18, 1),
    ('Bain', 'son of Bard', 19, 1),
    ('Bard', 'son of Brand', 20, 1),
    ('Brand', 'son of Bain', 21, 1),
    ('Thorin', 'son of Thrain', 22, 1),
    ('Dain', 'son of Nain', 23, 1),
    ('Balin', 'son of Fundin', 24, 1),
    ('Dwalin', 'son of Fundin', 25, 1),
    ('Oin', 'son of Groin', 26, 1),
    ('Gloin', 'son of Groin', 27, 1),
    ('Fili', 'son of Fundin', 28, 1),
    ('Kili', 'son of Fundin', 29, 1),
    ('Bifur', 'son of Bombur', 30, 1),
    ('Bofur', 'son of Bombur', 31, 1),
    ('Bombur', 'son of Bofur', 32, 1),
    ('Borin', 'son of Farin', 33, 1),
    ('Farin', 'son of Nori', 34, 1),
    ('Nori', 'son of Gror', 35, 1),
    ('Dori', 'son of Garin', 36, 1),
    ('Ori', 'son of Dori', 37, 1),
    ('Gimli', 'son of Gloin', 38, 1),
    ('Gloin', 'son of Groin', 39, 1),
    ('Oin', 'son of Groin', 40, 1),
    ('Balin', 'son of Fundin', 41, 1),
    ('Dwalin', 'son of Fundin', 42, 1),
    ('Fili', 'son of Fundin', 43, 1),
    ('Kili', 'son of Fundin', 44, 1),
    ('Bifur', 'son of Bombur', 45, 1),
    ('Bofur', 'son of Bombur', 46, 1),
    ('Bombur', 'son of Bofur', 47, 1),
    ('Borin', 'son of Farin', 48, 1),
    ('Farin', 'son of Nori', 49, 1),
    ('Nori', 'son of Gror', 50, 1),
    ('Dori', 'son of Garin', 51, 1),
    ('Ori', 'son of Dori', 52, 1),
    ('Gimli', 'son of Gloin', 53, 1),
    ('Gloin', 'son of Groin', 54, 1),
    ('Oin', 'son of Groin', 55, 1),
    ('Balin', 'son of Fundin', 56, 1),
    ('Dwalin', 'son of Fundin', 57, 1),
    ('Fili', 'son of Fundin', 58, 1);